"""add elo rating system

Revision ID: 08d02d8bf1f3
Revises: b9939c548c62
Create Date: 2026-01-23 16:40:27.633986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d02d8bf1f3'
down_revision = 'b9939c548c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elo_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('elo_before', sa.Integer(), nullable=False),
    sa.Column('elo_after', sa.Integer(), nullable=False),
    sa.Column('elo_change', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'match_id', name='unique_user_match_elo')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elo_rating', sa.Integer(), nullable=False, server_default='1200'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('elo_rating')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.alter_column('tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('elo_history')
    # ### end Alembic commands ###
