"""add sets_to_win to tournament

Revision ID: b9939c548c62
Revises: 749efbc9d050
Create Date: 2026-01-21 12:19:00.787092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9939c548c62'
down_revision = '749efbc9d050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sets_to_win', sa.Integer(), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('sets_to_win')

    # ### end Alembic commands ###
